import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

import { Card, EmptyState, ErrorState, LoadingState, PageHeader, PageShell } from '../components/PageShell.jsx';
import { ApiRequestError } from '../services/apiClient.js';
import { fetchRecommendations, fetchRoles } from '../services/career.service.js';
import { toMessage } from '../utils/errorMessage.js';

/**
 * /careers — roles ranked against the student's CareerTwin.
 *
 * Every number here comes from the backend. The scoring weights, the bands
 * and the per-dimension breakdown are all computed server-side and shipped
 * with the response precisely so they can be shown rather than trusted; this
 * page's job is to show them, not to have an opinion of its own.
 */

const LOAD_STATUS = { LOADING: 'loading', READY: 'ready', FAILED: 'failed' };

export function CareersPage() {
  const [data, setData] = useState(null);
  const [catalogue, setCatalogue] = useState(null);
  const [loadStatus, setLoadStatus] = useState(LOAD_STATUS.LOADING);
  const [loadError, setLoadError] = useState(null);
  /** True when the refusal was "you have no CareerTwin yet". */
  const [needsTwin, setNeedsTwin] = useState(false);
  const [includeAll, setIncludeAll] = useState(false);

  const load = useCallback(
    async (signal) => {
      setLoadStatus(LOAD_STATUS.LOADING);
      setLoadError(null);
      setNeedsTwin(false);

      try {
        // The catalogue is reference data every student sees, so it loads
        // even when there is no twin to rank it against. That is what makes
        // the no-twin state useful rather than blank.
        const [recommendations, roles] = await Promise.allSettled([
          fetchRecommendations({ includeAll, signal }),
          fetchRoles({ signal }),
        ]);
        if (signal?.aborted) return;

        if (roles.status === 'fulfilled') setCatalogue(roles.value);

        if (recommendations.status === 'fulfilled') {
          setData(recommendations.value);
          setLoadStatus(LOAD_STATUS.READY);
          return;
        }

        const error = recommendations.reason;
        if (error instanceof ApiRequestError && error.errorCode === 'CAREER_TWIN_NOT_FOUND') {
          setNeedsTwin(true);
          setLoadStatus(LOAD_STATUS.READY);
          return;
        }

        throw error;
      } catch (error) {
        if (signal?.aborted) return;

        setLoadError(toMessage(error, 'Your career matches could not be loaded.'));
        setLoadStatus(LOAD_STATUS.FAILED);
      }
    },
    [includeAll],
  );

  useEffect(() => {
    const controller = new AbortController();
    load(controller.signal);
    return () => controller.abort();
  }, [load]);

  // Only the first load replaces the page. A refresh — ticking "Include weak
  // matches" — keeps the current list on screen, so the checkbox the student
  // just used stays mounted and keeps keyboard focus.
  const isRefreshing = loadStatus === LOAD_STATUS.LOADING && data !== null;

  if (loadStatus === LOAD_STATUS.LOADING && !isRefreshing) {
    return (
      <PageShell>
        <LoadingState label="Working out which roles fit you…" rows={3} />
      </PageShell>
    );
  }

  if (loadStatus === LOAD_STATUS.FAILED) {
    return (
      <PageShell>
        <ErrorState
          title="Your career matches could not be loaded"
          message={loadError}
          onRetry={() => load()}
        />
      </PageShell>
    );
  }

  if (needsTwin) {
    return (
      <PageShell>
        <PageHeader title="Career matches">
          Roles ranked against what Nexora has seen you demonstrate.
        </PageHeader>

        <div className="flex flex-col gap-5">
          <Card title="Build your CareerTwin first">
            <div className="flex flex-col gap-4">
              <EmptyState>
                Matches are measured against your CareerTwin, and you have not built one yet.
              </EmptyState>

              <div>
                <Link
                  to="/career-twin"
                  className="inline-block rounded-xl bg-brand px-5 py-3 text-sm font-semibold text-on-brand transition-colors duration-200 hover:bg-brand-soft"
                >
                  Go to CareerTwin
                </Link>
              </div>
            </div>
          </Card>

          <RoleCatalogue catalogue={catalogue} />
        </div>
      </PageShell>
    );
  }

  return (
    <PageShell>
      <PageHeader title="Career matches">
        {data.matches.length > 0
          ? `${data.matches.length} role${data.matches.length === 1 ? '' : 's'} ranked against your CareerTwin.`
          : 'No role matched strongly enough to recommend yet.'}
      </PageHeader>

      <div className="flex flex-col gap-5">
        <Card
          title="Ranked roles"
          description="Scored from your CareerTwin against a curated catalogue. Nothing here is generated by an AI."
          actions={
            <label className="flex cursor-pointer items-center gap-2 text-sm text-ink-muted">
              <input
                type="checkbox"
                checked={includeAll}
                onChange={(event) => setIncludeAll(event.target.checked)}
                className="size-4 rounded border-orange-300 accent-[var(--color-brand)]"
              />
              Include weak matches
            </label>
          }
        >
          {data.matches.length === 0 ? (
            <EmptyState>
              Nothing scored highly enough to suggest. Adding projects or analysing a resume gives
              Nexora more to match on — or tick “Include weak matches” to see the full ranking
              anyway.
            </EmptyState>
          ) : (
            <ul
              aria-busy={isRefreshing}
              className={`flex flex-col gap-3 transition-opacity duration-200 ${isRefreshing ? 'opacity-60' : ''}`}
            >
              {data.matches.map((match) => (
                <li key={match.roleId}>
                  <MatchCard match={match} />
                </li>
              ))}
            </ul>
          )}
        </Card>

        <Method method={data.method} basedOn={data.basedOn} />

        <RoleCatalogue catalogue={catalogue} />
      </div>
    </PageShell>
  );
}

/**
 * One ranked role.
 *
 * The score, the band and the explanation are all the server's. The bar is a
 * rendering of `match.score` and nothing else — no smoothing, no curve, no
 * second opinion about what the number means.
 */
function MatchCard({ match }) {
  return (
    <article className="animate-rise rounded-xl border border-orange-100 bg-orange-50/30 p-4">
      <div className="flex flex-wrap items-baseline justify-between gap-2">
        <h3 className="text-base font-semibold text-ink break-words">{match.title}</h3>
        <p className="text-sm font-semibold text-brand-text">
          {match.score}
          <span className="text-xs font-normal text-ink-muted">/100 · {match.band}</span>
        </p>
      </div>

      {match.summary ? <p className="mt-1 text-sm text-ink-muted break-words">{match.summary}</p> : null}

      <div
        role="img"
        aria-label={`Match score ${match.score} out of 100 — ${match.band}`}
        className="mt-3 h-2 w-full overflow-hidden rounded-full bg-orange-100"
      >
        <div
          className="h-full rounded-full bg-brand transition-[width] duration-500"
          style={{ width: `${match.score}%` }}
        />
      </div>

      {match.bandDescription ? (
        <p className="mt-2 text-xs text-ink-muted break-words">{match.bandDescription}</p>
      ) : null}

      {match.explanation ? <p className="mt-2 text-sm text-ink break-words">{match.explanation}</p> : null}

      <Dimensions dimensions={match.dimensions} />

      <SkillLists match={match} />

      <div className="mt-3 flex flex-wrap gap-2">
        <Link
          to={`/careers/${match.roleId}/skill-gap`}
          className="inline-flex min-h-[44px] items-center rounded-lg border border-orange-200 px-3 py-2.5 text-xs font-semibold text-brand-text transition-colors duration-200 hover:border-brand hover:bg-orange-50"
        >
          See the skill gap
        </Link>
        <Link
          to={`/careers/${match.roleId}/roadmap`}
          className="inline-flex min-h-[44px] items-center rounded-lg border border-orange-200 px-3 py-2.5 text-xs font-semibold text-brand-text transition-colors duration-200 hover:border-brand hover:bg-orange-50"
        >
          See the roadmap
        </Link>
      </div>
    </article>
  );
}

/**
 * The per-dimension breakdown, with the weight each carried.
 *
 * Shown because a student who disagrees with a score should be able to see
 * which part of it they disagree with. The weights come from the response,
 * not from a copy kept here.
 */
function Dimensions({ dimensions }) {
  if (!dimensions) return null;

  const entries = Object.entries(dimensions);
  if (entries.length === 0) return null;

  return (
    <dl className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4">
      {entries.map(([name, detail]) => (
        <div key={name} className="rounded-lg border border-orange-100 bg-surface p-2">
          <dt className="text-ink-muted capitalize">{name.replace(/([A-Z])/g, ' $1')}</dt>
          <dd className="font-semibold text-ink">
            {detail.value}%
            {detail.weight !== undefined ? (
              <span className="ml-1 font-normal text-ink-muted">
                (weight {Math.round(detail.weight * 100)}%)
              </span>
            ) : null}
          </dd>
        </div>
      ))}
    </dl>
  );
}

function SkillLists({ match }) {
  const lists = [
    ['Required, and you have it', match.matchedRequired?.map(nameOf)],
    ['Required, and missing', match.missingRequired],
    ['Preferred, and you have it', match.matchedPreferred?.map(nameOf)],
    ['Preferred, and missing', match.missingPreferred],
  ].filter(([, items]) => items?.length > 0);

  if (lists.length === 0) return null;

  return (
    <div className="mt-3 flex flex-col gap-2">
      {lists.map(([label, items]) => (
        <div key={label} className="text-xs">
          <p className="font-semibold text-ink-muted">{label}</p>
          <p className="mt-0.5 text-ink">{items.join(', ')}</p>
        </div>
      ))}
    </div>
  );
}

/** A matched skill arrives as an object; a missing one as a bare name. */
function nameOf(entry) {
  return typeof entry === 'string' ? entry : (entry?.name ?? entry?.skill ?? '');
}

/**
 * Where the numbers came from.
 *
 * The backend returns this with every response on the grounds that a
 * recommendation a student cannot interrogate is one they have to take on
 * faith. Hiding it in the client would waste that.
 */
function Method({ method, basedOn }) {
  if (!method) return null;

  return (
    <Card title="How this was worked out">
      <dl className="flex flex-col gap-2 text-sm">
        <Row label="Method">
          {method.deterministic ? 'Deterministic' : 'Non-deterministic'}
          {method.usesAi ? ', uses AI' : ', no AI involved'}
        </Row>

        {method.catalogueSource ? (
          <Row label="Catalogue">
            {method.catalogueSource.type ?? 'curated'}
            {method.version ? ` · version ${method.version}` : ''}
            {method.rolesConsidered ? ` · ${method.rolesConsidered} roles considered` : ''}
          </Row>
        ) : null}

        {method.weights ? (
          <Row label="Weights">
            {Object.entries(method.weights)
              .map(([name, weight]) => `${name} ${Math.round(weight * 100)}%`)
              .join(' · ')}
            {method.weightsVersion ? ` (version ${method.weightsVersion})` : ''}
          </Row>
        ) : null}

        {basedOn ? (
          <Row label="Based on">
            {basedOn.skillsConsidered} skill
            {basedOn.skillsConsidered === 1 ? '' : 's'} from your CareerTwin
          </Row>
        ) : null}
      </dl>
    </Card>
  );
}

function Row({ label, children }) {
  return (
    <div className="flex flex-wrap gap-x-2">
      <dt className="shrink-0 font-medium text-ink-muted">{label}</dt>
      <dd className="min-w-0 text-ink">{children}</dd>
    </div>
  );
}

/** Every role in the catalogue, for a student whose match list is short. */
function RoleCatalogue({ catalogue }) {
  if (!catalogue?.roles?.length) return null;

  return (
    <Card
      title="All roles"
      description="The full catalogue. Every student sees the same list — only the ranking above is yours."
    >
      <ul className="flex flex-col gap-2">
        {catalogue.roles.map((role) => (
          <li
            key={role.id}
            className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-orange-100 bg-orange-50/30 p-3"
          >
            <div className="min-w-0">
              <p className="font-semibold text-ink">{role.title}</p>
              <p className="text-xs text-ink-muted">{role.summary}</p>
            </div>

            <Link
              to={`/careers/${role.id}/skill-gap`}
              className="inline-flex min-h-[44px] shrink-0 items-center rounded-lg border border-orange-200 px-3 py-2.5 text-xs font-semibold text-brand-text transition-colors duration-200 hover:border-brand hover:bg-orange-50"
            >
              Skill gap
            </Link>
          </li>
        ))}
      </ul>
    </Card>
  );
}
