import {
  EVIDENCE_STRENGTH,
  EVIDENCE_STRENGTH_ORDER,
} from '../evidence/evidence.js';
import { findSkillByAlias } from '../skills/skillOntology.js';
import { CAREER_ROLES } from '../careers/roleCatalogue.js';
import { skillKey, skillDisplayName } from '../skills/skillKey.js';

/**
 * Task 07 — CareerTwin Intelligence Projection Engine
 *
 * Provides deterministic, explainable derivations for:
 * 1. Skill State & Strength Aggregation
 * 2. Normalized Proficiency with Conflict Resolution
 * 3. Evidence-Grounded Confidence Scoring [0.10 - 1.00]
 * 4. Target Role Relevance & Competency Mapping
 * 5. Deterministic, Reproducible Projection from Canonical Student State
 */

/**
 * Derives the confidence score for a skill based on evidence strength,
 * corroboration across independent sources, assessment performance, and recency.
 *
 * Confidence is strictly bounded [0.10, 1.00] and is never generated by an AI model.
 *
 * @param {object} params
 * @param {string} params.strength 'claimed' | 'supported' | 'verified'
 * @param {Array<object>} params.evidence List of evidence items supporting this skill
 * @param {Date|string|null} [params.lastUpdate] Timestamp of latest evidence
 * @returns {number} Score between 0.10 and 1.00 rounded to 2 decimal places.
 */
export function deriveConfidence({ strength, evidence = [], lastUpdate = null }) {
  // 1. Base confidence anchored to strongest evidence level
  let base = 0.35;
  if (strength === EVIDENCE_STRENGTH.VERIFIED) {
    base = 0.90;
  } else if (strength === EVIDENCE_STRENGTH.SUPPORTED) {
    base = 0.65;
  }

  // 2. Corroboration bonus: +0.05 per additional independent source beyond the first (capped at +0.10)
  const distinctSources = new Set(evidence.map((e) => e.source || 'unknown')).size;
  const corroborationBonus = Math.min(0.10, Math.max(0, (distinctSources - 1) * 0.05));

  // 3. High assessment/verification performance bonus: +0.05 if any verified item has score >= 0.85
  let scoreBonus = 0;
  for (const item of evidence) {
    if (item.verified && typeof item.score === 'number' && item.score >= 0.85) {
      scoreBonus = 0.05;
      break;
    }
  }

  // 4. Staleness penalty: -0.10 if last evidence update was > 180 days ago
  let stalenessPenalty = 0;
  if (lastUpdate) {
    const updateTime = new Date(lastUpdate).getTime();
    if (!Number.isNaN(updateTime)) {
      const ageInDays = (Date.now() - updateTime) / (1000 * 60 * 60 * 24);
      if (ageInDays > 180) {
        stalenessPenalty = -0.10;
      }
    }
  }

  const rawScore = base + corroborationBonus + scoreBonus + stalenessPenalty;
  return Math.max(0.10, Math.min(1.00, Number(rawScore.toFixed(2))));
}

/**
 * Derives normalized proficiency level ('beginner' | 'intermediate' | 'advanced')
 * with strict conflict resolution:
 *
 * Conflict Resolution Invariant:
 * A student cannot be awarded 'advanced' proficiency based solely on self-declaration
 * or resume extraction without verified assessment or extensive supported evidence.
 *
 * @param {object} params
 * @param {string} params.strength 'claimed' | 'supported' | 'verified'
 * @param {string|null} [params.selfDeclaredLevel] Student's stated level on profile
 * @param {Array<object>} [params.evidence] Supporting evidence items
 * @returns {'beginner'|'intermediate'|'advanced'}
 */
export function deriveProficiency({ strength, selfDeclaredLevel = null, evidence = [] }) {
  const declared = (selfDeclaredLevel || '').toLowerCase().trim();

  // 1. Verified Evidence takes top authority
  if (strength === EVIDENCE_STRENGTH.VERIFIED) {
    const highPass = evidence.some(
      (e) => e.verified && typeof e.score === 'number' && e.score >= 0.85,
    );
    if (highPass || declared === 'advanced' || declared === 'expert') {
      return 'advanced';
    }
    return 'intermediate';
  }

  // 2. Supported Evidence (Projects & Certifications)
  if (strength === EVIDENCE_STRENGTH.SUPPORTED) {
    if (declared === 'beginner') {
      return 'beginner';
    }
    // Advanced requires verified assessment; supported can achieve intermediate
    return 'intermediate';
  }

  // 3. Claimed Only (Profile entry or unverified Resume mention)
  if (declared === 'intermediate') {
    return 'intermediate';
  }
  // Conflict resolution rule: if student claims advanced/expert with no supporting evidence,
  // cap at intermediate
  if (declared === 'advanced' || declared === 'expert') {
    return 'intermediate';
  }

  return 'beginner';
}

/**
 * Maps a canonical skill key to role relevance against the student's target roles.
 *
 * @param {string} key Normalized skill key (e.g. 'nodejs')
 * @param {Array<object>} [targetRoles] Student's stated target roles [{ title: 'Backend Developer' }]
 * @param {Array<object>} [roleCatalogue] Career roles catalogue
 * @returns {{ isTargetRoleSkill: boolean, relevanceTier: 'required'|'preferred'|'transferable'|'general', targetRolesMatched: string[] }}
 */
export function deriveRoleRelevance(key, targetRoles = [], roleCatalogue = CAREER_ROLES) {
  if (!key || !targetRoles || targetRoles.length === 0) {
    return {
      isTargetRoleSkill: false,
      relevanceTier: 'general',
      targetRolesMatched: [],
    };
  }

  const roleTitles = targetRoles.map((r) => (r.title || r).toLowerCase().trim());
  const matchingRoles = roleCatalogue.filter((role) =>
    roleTitles.some((t) => role.title.toLowerCase().includes(t) || t.includes(role.title.toLowerCase())),
  );

  if (matchingRoles.length === 0) {
    return {
      isTargetRoleSkill: false,
      relevanceTier: 'general',
      targetRolesMatched: [],
    };
  }

  const requiredIn = [];
  const preferredIn = [];
  const transferableIn = [];

  for (const role of matchingRoles) {
    const reqKeys = (role.requiredSkills || []).map((s) => skillKey(s));
    const prefKeys = (role.preferredSkills || []).map((s) => skillKey(s));
    const relKeys = (role.relatedTechnologies || []).map((s) => skillKey(s));

    if (reqKeys.includes(key)) {
      requiredIn.push(role.title);
    } else if (prefKeys.includes(key)) {
      preferredIn.push(role.title);
    } else if (relKeys.includes(key)) {
      transferableIn.push(role.title);
    }
  }

  if (requiredIn.length > 0) {
    return {
      isTargetRoleSkill: true,
      relevanceTier: 'required',
      targetRolesMatched: requiredIn,
    };
  }

  if (preferredIn.length > 0) {
    return {
      isTargetRoleSkill: true,
      relevanceTier: 'preferred',
      targetRolesMatched: preferredIn,
    };
  }

  if (transferableIn.length > 0) {
    return {
      isTargetRoleSkill: true,
      relevanceTier: 'transferable',
      targetRolesMatched: transferableIn,
    };
  }

  return {
    isTargetRoleSkill: false,
    relevanceTier: 'general',
    targetRolesMatched: [],
  };
}

/**
 * Projects a raw aggregated skill into a fully qualified CareerTwin skill projection.
 *
 * @param {object} entry
 * @param {string} entry.key Normalized skill key
 * @param {string} entry.name Display name
 * @param {string} entry.strength Strongest evidence strength
 * @param {string|null} [entry.selfDeclaredLevel] Profile level
 * @param {Array<object>} entry.evidence Evidence array
 * @param {Array<object>} [targetRoles] Student's stated target roles
 * @returns {object} CareerTwin skill subdocument
 */
export function projectTwinSkill(entry, targetRoles = []) {
  // 1. Resolve canonical ontology metadata
  const ontologySkill = findSkillByAlias(entry.name) || findSkillByAlias(entry.key);
  const skillId = ontologySkill ? ontologySkill.id : `sk_${entry.key}`;
  const canonicalName = entry.name || (ontologySkill ? ontologySkill.name : skillDisplayName(entry.name));
  const category = ontologySkill ? ontologySkill.category : 'general';

  // 2. Identify latest evidence timestamp
  let latestTimestamp = null;
  for (const item of entry.evidence || []) {
    if (item.recordedAt) {
      const t = new Date(item.recordedAt).getTime();
      if (!Number.isNaN(t) && (!latestTimestamp || t > latestTimestamp)) {
        latestTimestamp = t;
      }
    }
  }

  const lastUpdate = latestTimestamp ? new Date(latestTimestamp) : null;

  // 3. Derive state & strength
  const strength = entry.strength || EVIDENCE_STRENGTH.CLAIMED;
  const state = strength;

  // 4. Derive confidence & proficiency
  const confidence = deriveConfidence({ strength, evidence: entry.evidence, lastUpdate });
  const proficiency = deriveProficiency({
    strength,
    selfDeclaredLevel: entry.selfDeclaredLevel,
    evidence: entry.evidence,
  });

  // 5. Derive role relevance
  const roleRelevance = deriveRoleRelevance(entry.key, targetRoles);

  // 6. Distinct sources
  const sourceSet = new Set((entry.evidence || []).map((e) => e.source || 'unknown'));
  const sources = Array.from(sourceSet);
  const sourceCount = sources.length;

  return {
    key: entry.key,
    name: canonicalName,
    skillId,
    category,
    strength,
    state,
    proficiency,
    confidence,
    selfDeclaredLevel: entry.selfDeclaredLevel || null,
    evidence: entry.evidence || [],
    sources,
    sourceCount,
    lastUpdate,
    roleRelevance,
  };
}
